article/urls.py
#!/usr/bin/env python 
# -*- coding:utf-8 -*-
from django.urls import path
from . import views
app_name = 'article'    #正在部署的应用名称

urlpatterns = [
    #用户请求 aiticle/ 链接时，会调用views.py中的article_list 函数，并返回渲染后的对象，参数name用于反查url地址，相当于给url起了个名字
    path('article/', views.article_list, name='article_list'),
    path('article/detail<int:article_id>/', views.article_detail, name='article_detail'),
    path('article/create/',views.article_create,name='article_create'),
    path('article/delete<int:article_id>/', views.article_delete, name='article_delete'),
    path('article/update<int:article_id>/', views.article_update, name='article_update'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('article.urls', namespace='articale')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    #参数article/分配了app的访问路径，includejji将路径分发给下一步处理，namespace 可以保证反查到唯一的url，即使不同的app使用了相同的url
    path('password-reset/', include('password_reset.urls')),
    path('comment/', include('comment.urls', namespace='comment')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
#!/usr/bin/env python 
# -*- coding:utf-8 -*-
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:user_id>', views.user_delete, name='delete'),
    #用户信息
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

templates/base.html
<!-- 载入静态文件 -->
{% load staticfiles %}

<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="en">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="UTF-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

    <!-- 引入monikai.css -->
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
</head>
<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
    <!-- 预留具体页面的位置 -->
    {% block content %}{% endblock content %}
    <!-- 引入注脚 -->
    {% include 'footer.html' %}
    <!-- bootstrap.js 依赖jquery.js 和 popper.js,因此在这里引入 -->
    <script src="{% static 'jquery/jquery-3.4.1.js' %}"></script>
    <script src="{% static 'popper/popper.js' %}"></script>
    <!-- 引入bootstrap的js文件 -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- 引入layer.js -->
    <script src="{% static 'layer/layer.js' %}"></script>
</body>

</html>

templates/footer.html
{% load staticfiles %}

<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; www.dusaiphoto.com 2019</p>
    </div>
</footer>

templates/header.html
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <!-- 导航栏商标 -->
        <a class="navbar-brand" href="{% url 'article:article_list' %}">我的博客</a>

        <!-- 导航栏入口 -->
        <div>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_create' %}">写文章</a>
                </li>
                <!-- 条目 -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_list' %}">文章</a>
                </li>

                <!-- django 的 if 模板语句 -->
                {% if user.is_authenticated %}
                    <!-- 如果用户已经登录,则显示用户名下拉框 -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <!-- 新增删除用户入口 -->
                            <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
                            <a class="dropdown-item" href="{% url 'userprofile:logout' %}">退出登录</a>
                            <a class="dropdown-item" href="{% url 'userprofile:edit' user.id %}">个人信息</a>
                        </div>
                    </li>
                <!-- 如果用户未登录，则显示'登录' -->
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
                    </li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>

<!-- 新增 -->
{% if user.is_authenticated %}
    <script>
        function user_delete() {
            //调用 layer 弹窗组件
            layer.open({
                title: '确认删除',
                content: '确认删除用户资料吗？',
                yes: function(index,layero) {
                    location.href="{% url 'userprofile:delete' user.id %}"
                },
            })
        }
    </script>
{% endif %}