article/urls.py
#!/usr/bin/env python 
# -*- coding:utf-8 -*-
from django.urls import path
from . import views
app_name = 'article'    #正在部署的应用名称

urlpatterns = [
    #用户请求 aiticle/ 链接时，会调用views.py中的article_list 函数，并返回渲染后的对象，参数name用于反查url地址，相当于给url起了个名字
    path('article/', views.article_list, name='article_list'),
    path('article/detail<int:article_id>/', views.article_detail, name='article_detail'),
    path('article/create/',views.article_create,name='article_create'),
    path('article/delete<int:article_id>/', views.article_delete, name='article_delete'),
    path('article/update<int:article_id>/', views.article_update, name='article_update'),
]

comment/urls.py
#!/usr/bin/env python 
# -*- coding:utf-8 -*-

from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    # 发表评论
    path('post_comment/<int:article_id>/', views.post_comment, name='post_comment'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('article.urls', namespace='articale')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    #参数article/分配了app的访问路径，includejji将路径分发给下一步处理，namespace 可以保证反查到唯一的url，即使不同的app使用了相同的url
    path('password-reset/', include('password_reset.urls')),
    path('comment/', include('comment.urls', namespace='comment')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
#!/usr/bin/env python 
# -*- coding:utf-8 -*-
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:user_id>', views.user_delete, name='delete'),
    #用户信息
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

article/models.py
from django.db import models

from django.contrib.auth.models import User

from django.utils import timezone   #timezone 用于处理时间相关事务

from django.urls import reverse

class ArticleColumn(models.Model):
    """栏目的 Model"""
    # 栏目标题
    title = models.CharField(max_length=100, blank=True)
    # 创建时间
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


#博客文章数据类型
class ArticlePost(models.Model):
    #文章作者，在船舰多对一的关系中，需要在外键的第二个参数中on_delete=models.CASCADE 主外关系键中，级联删除，也就是删除主表的数据的时候从表中的数据页随着一起删除
    #使用ForeignKey 定义一个关系，这将告诉Django，每个（或多个）ArticlePost 对象都关联到一个User对象
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    #文章标题，models.CharFiled 为字符串字段，用于保存较短的字符串，比如标题
    title = models.CharField(max_length=100)

    #文章正文，保存大量文本使用TextFiled
    body = models.TextField()

    #文章创建时间,参数 default=timezone.now 指定其在创建数据时将默认写入当前的时间
    created = models.DateTimeField(default=timezone.now)

    #文章更新时间,参数 auto_now=True 指定每次数据更新时自动写入当前时间
    updated = models.DateTimeField(auto_now=True)
    #存储浏览量，PositiveIntegerField 是用于存储正整数的字段，default=0设定初始值从0开始
    total_views = models.PositiveIntegerField(default=0)

    #文章栏目的 '一对多' 外键
    column = models.ForeignKey(
        ArticleColumn,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='article'
    )
    #内部类Class Meta 用于给model 定义元数据
    class Meta:
        #ordering 指定模型返回的数据的排列顺序
        #'-created'表名数据应该以倒序排列
        ordering = ('-created',)

    def __str__(self):
        return self.title

    #获取文章地址
    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

article/forms.py
#!/usr/bin/env python 
# -*- coding:utf-8 -*-
#引入表单类
from django import forms
#引入文章模型
from .models import ArticlePost

#写文章的表单类
class ArticlePostForm(forms.ModelForm):
    class Meta:
        #指明数据模型来源
        model = ArticlePost
        #定义表单包含的字段
        fields = ('title', 'body')

article/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import ArticlePost
import markdown
from .forms import ArticlePostForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db.models import Q   #引入Q对象
from comment.models import Comment
from .models import ArticleColumn #引入栏目Model
#引入分页模块
from django.core.paginator import Paginator

def article_list(request):
    # return HttpResponse('hello world!')
#每一个视图表现为一个简单的python函数，它必须要做两件事：返回一个包含请求页面内容的HttpResponse对象，或者抛出一个异常
#视图函数中的 request 与网页发来的请求相关，里面包含 get\post的内容、用户浏览器、系统等信息，django调用article_list函数时返回一个HttpResponse对象

    search = request.GET.get('search')
    order = request.GET.get('order')

    #用户搜索逻辑
    if search:
        #根据 GET 请求中查询条件
        #返回不同排序的对象数组
        if order == 'total_views':
            #用 Q 对象，进行联合搜索
            article_list = ArticlePost.objects.filter(
                Q(title__icontains=search) |
                Q(body__icontains=search)
            ).order_by('-total_views')
        else:
            article_list = ArticlePost.objects.filter(
                Q(title__icontains=search) |
                Q(body__icontains=search)
            )
    else:
        #将 search 参数重置为空
        search = ''
        if order == 'total_views':
            article_list = ArticlePost.objects.all().order_by('-total_views')
        else:
            article_list = ArticlePost.objects.all()
    # article_list = ArticlePost.objects.all()    #取出所有博客文章
    #每页显示 1 篇文章
    paginator = Paginator(article_list, 3)
    # 获取 URL 中的页码
    page = request.GET.get('page')
    #将导航对象相应的页码内容返回给 articles
    articles = paginator.get_page(page)

    context = {'articles': articles, 'order': order, 'search':search }    #需要传递给模板 templeates 的对象
    # render 函数:载入模板，并返回 context 对象
    return render(request, 'article/list.html', context)

#文章详情
def article_detail(request, article_id):
    #取出响应的文章
    article = ArticlePost.objects.get(id=article_id)
    #取出文章评论
    comments = Comment.objects.filter(article=article_id)

    #浏览量 +1,  update_fields=[]  指定了数据库只更新total_views字段，优化执行效率
    article.total_views += 1
    article.save(update_fields=['total_views'])

    #将markdown 语法渲染成html样式
    md = markdown.Markdown(
        extensions = [
            #包含 缩写、表格等常用扩展
            'markdown.extensions.extra',
            #语法高亮扩展
            'markdown.extensions.codehilite',

            #目录扩展
            'markdown.extensions.toc',]
    )
    #用convert()方法将正文渲染为html 页面，通过md.toc 将目录传递给模板
    article.body = md.convert(article.body)

    #需要传递给模板的对象
    context = {'article': article, 'toc': md.toc, 'comments': comments}
    return render(request, 'article/detail.html', context)

#检查登录
@login_required(login_url='/userprofile/login/')
#写文章的视图
def article_create(request):
    #判断用户是否提交数据
    if request.method == 'POST':
        #将提交的数据赋值到表单实例中
        article_post_form = ArticlePostForm(data=request.POST)
        #判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            #保存数据，但暂时不提交到数据库中
            new_article = article_post_form.save(commit=False)
            #如果你进行过删除数据库表的操作，可能会找不到 id=1 的作者
            #此时请重新创建用户,并指定目前登录的用户为作者
            new_article.author = User.objects.get(id=request.user.id)
            #将新文章保存到数据库中
            if request.POST['column'] != 'none':
                new_article.column = ArticleColumn.objects.get(id=request.POST['column'])
            new_article.save()
            #完成后返回到文章列表
            return redirect('article:article_list')
        #如果数据不合法，返回错误信息
        else:
            return HttpResponse('表单内容有误,请重新填写.')
    #如果用户请求获取数据
    else:
        #创建表单类实例
        article_post_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()
        #赋值上下文
        context = {'article_post_form': article_post_form, 'columns': columns }
        #返回模板
        return render(request, 'article/create.html', context)

@login_required(login_url='/userprofile/login/')
#删除文章
def article_delete(request, article_id):
    #根据id 获取需要删除的文章
    article = ArticlePost.objects.get(id=article_id)
    if request.user != article.author:
        return HttpResponse('抱歉, 你没有权限操作.')
    else:
        #调用 .delete() 方法删除文章
        article.delete()
        #完成删除后返回文章列表
        return redirect('article:article_list')

@login_required(login_url='/userprofile/login/')
#更新文章
def article_update(request,article_id):
    '''
    更新文章的视图函数通过POST方法提交表单，更新title\body 字段
    GET 方法进入初始表单页面，article_id 是文章的id
    :param request:
    :param article_id:
    :return:
    '''

    #获取需要修改的具体文章对象
    article = ArticlePost.objects.get(id=article_id)
    #过滤非作者的用户
    if request.user != article.author:
        return HttpResponse('抱歉，你无权修改这篇文章.')

    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        #判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            #保存新写入的 title \body ,数据并保存
            article.title = request.POST['title']
            article.body = request.POST['body']
            if request.POST['column'] != 'none':
                article.column = ArticleColumn.objects.get(id=request.POST['column'])
            else:
                article.column = None
            article.save()
            return redirect('article:article_detail', article_id=article_id)
        #如果数据不合法，返回错误信息
        else:
            return HttpResponse('表单内容有误，请重新填写')
    # GET请求
    else:
        article_post_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()
        #赋值上下文，将article 文章对象页传进去，以便提取旧的内容
        context = {'article': article, 'article_post_form': article_post_form, 'columns': columns }
        return render(request, 'article/update.html', context)

templates/article/create.html
<!-- extends 表名 此页 继承自 base.html 文件 -->
{% extends 'base.html' %}{% load staticfiles %}
<!-- 写入base.html 中定义的 title-->
{% block title %} 写文章 {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
            <form method="post" action=".">
                <!-- django 中需要POST 数据的地方都必须有 csrf-token -->
                {% csrf_token %}
                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">文章标题</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <!-- 文章栏目 -->
                <div class="form-group">
                    <label for="column">栏目</label>
                    <select class="form-control"
                            id="column"
                            name="column"
                            >
                            <option value="none">请选择栏目..</option>
                        {% for column in columns %}
                            <option value="{{ colum.id }}">{{ column }}</option>
                        {% endfor %}
                    </select>
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/article/detail.html
<!-- exends 表明此页面继承自 base.html 文件 -->
{% extends 'base.html' %}
{% load staticfiles %}

<!-- 写入base.html 中定义的 title -->
{% block title %}
    文章详情
{% endblock title %}

<!-- 写入base.html 中定义的 content -->
{% block content %}

<!-- 文章详情 -->
<div class="container">
    <div class="row">
        <div class="col-9">
            <!-- 标题及作者 -->
            <h1 class="mt-4 mb-4">{{ article.title }}</h1>
            <div class="alert alert-success">
                <div>
                    作者:{{ article.author }}
                    {% if user == article.author %}
                         . <a href="#" onclick="confirm_delete()">删除文章</a>
                         . <a href="{% url 'article:article_update' article.id %}">编辑文章</a>
                    {% endif %}
                </div>
                <div>
                    浏览: {{ article.total_views }}
                </div>
            </div>
            <!-- 文章正文 -->
            <div class="col-12">
                <p>{{ article.body|safe }}</p>
            </div>

            <!-- 发表评论 -->
            <hr>
            {% if user.is_authenticated %}
                <div>
                    <form
                        action="{% url 'comment:post_comment' article.id %}"
                        method="POST"
                        >
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="body">
                                <strong>
                                    我也要发言:
                                </strong>
                            </label>
                            <textarea
                                type="text"
                                class="form-control"
                                id="body"
                                name="body"
                                rows="2"></textarea>
                        </div>
                        <!-- 提交按钮 -->
                        <button type="submit" class="btn btn-primary">发送</button>
                    </form>
                </div>
                <br>
            {% else %}
                <br>
                <h5 class="row justify-content-center">
                    请<a href="{% url 'userprofile:login' %}">登录</a>后回复
                </h5>
                <br>
            {% endif %}

            <!-- 显示评论 -->
            <h4>共有{{ comments.count }}条评论</h4>
            <div>
                {% for comment in comments %}
                    <hr>
                    <p>
                        <strong style="color: pink">
                            {{ comment.user }}
                        </strong>于
                        <span style="color: green">
                            {{ comment.created|date:'Y-m-d H:i:s' }}
                        </span>时说：
                    </p>
                    <pre style="font-family: inherit; font-size: lem;">
                        {{ comment.body }}
                    </pre>
                {% endfor %}
            </div>
        </div>

            <!-- 新增的目录 -->
            <div class="col-3 mt-4">
                <h4><strong>目录</strong></h4>
                <hr>
                <div>
                    {{ toc|safe }}
                </div>
            </div>
        </div>
    </div>

<script>
    //删除文章的函数
    function confirm_delete() {
        //调用layer 弹窗组件
        layer.open({
            //弹窗标题
            title: '确认删除',
            //正文
            content: '确认删除这篇文章吗？',
            //点击确定按钮后调用的回调函数
            yes: function(index, layero) {
                //指定应当前往的 url
                location.href="{% url 'article:article_delete' article.id %}"
            },
        })
    }
</script>

{% endblock content %}

templates/article/list.html
<!-- extends 表名此页面继承自 base.html 文件-->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入base.html 定义中的title -->
{% block title %}
    首页
{% endblock title %}

<!-- 写入base.html 中定义的 content -->
{% block content %}

<!-- 定义防止文章标题的div容器 -->
<div class="container">
    <!-- 修改, 面包屑的 href 增加 search 参数 -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}"search="{{ search }}">
                    最新
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}?order=total_views&search={{ search }}">
                    最热
                </a>
            </li>
        </ol>
    </nav>

    <!-- 新增搜索栏 -->
    <div class="row">
        <div class="col-auto mr-auto">
            <form class="form-inline">
                <label class="sr-only">content</label>
                <input type="text"
                       class="form-control mb-2 mr-sm-2"
                       name="search"
                       placeholder="搜索文章..."
                       required>
            </form>
        </div>
    </div>

    <!-- 新增, 搜索提示语 -->
    {% if search %}
        {% if articles %}
            <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下:</h4>
            <hr>
        {% else %}
            <H4>暂无<span style="color: red">"{{ search }}"</span>有关的文章.</H4>
            <hr>
        {% endif %}
    {% endif %}

    <!-- 列表循环 -->
    <div class="row mt-2">

        {% for article in articles %}
            <!-- 文章内容 -->
            <div class="col-12">
                <!-- 栏目 -->
                {% if article.column %}
                    <button type="button"
                            class="btn btn-sm mb-2
                                {% if article.column.title == 'Django' %}
                                    btn-success
                                {% elif article.column.title == 'Python' %}
                                    btn-danger
                                {% elif article.column.title == '日记' %}
                                    btn-warning
                                {% endif %}
                             "
                    >
                        {{ article.column }}
                    </button>
                {% endif %}

                <!-- 标题 -->
                <h4>
                    <b>
                        <a href="{% url 'article:article_detail' article.id %}"
                           style="color: black;"
                           >
                            {{ article.title }}
                        </a>
                    </b>
                </h4>
                <!-- 摘要 -->
                <div>
                    <p style="color: gray;">
                        {{ article.body|slice:'100' }}...
                    </p>
                </div>
                <!-- 注脚 -->
                <p>
                    <!-- 附加信息 -->
                    <span style="color: green;">
                        {{ article.total_views }} 浏览&nbsp;&nbsp;&nbsp;
                    </span>
                    <span style="color: blue;">
                        {{ article.created|date:'Y-m-d' }} 发布&nbsp;&nbsp;&nbsp;
                    </span>
                    <span style="color: darkred;">
                        {{ article.updated|date:'Y-m-d' }} 更新
                    </span>
                </p>
                <hr>
            </div>
        {% endfor %}
    </div>

    </div>
    <!-- 页码导航 -->
    <div class="pagination row">
        <div class="m-auto">
            <span class="step-links">
                <!-- 如果不是第一页，则显示上翻按钮 -->
                {% if articles.has_previous %}
                    <a href="?page=1&order={{ order }}&search={{ search }}" class="btn btn-success">
                        &laquo; 1
                    </a>
                    <span>...</span>
                <a href="?page={{ articles.previous_page_number }}&order={{ order }}&search={{ search }}"
                   class="btn btn-secondary"
                   >
                    {{ articles.previous_page_number }}
                </a>
                {% endif %}

                <!-- 当前页面 -->
                <span class="current btn btn-danger btn-lg">
                    {{ articles.number }}
                </span>

                <!-- 如果不是最末页,则显示下翻按钮 -->
                {% if articles.has_next %}
                    <a href="?page={{ articles.next_page_number }}&order={{ order }}&search={{ search }}"
                       class="btn btn-secondary"
                       >
                        {{ articles.next_page_number }}
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}&searcg={{ search }}"
                       class="btn btn-success"
                       >
                        {{ articles.paginator.num_pages }} &raquo;
                    </a>
                {% endif %}
            </span>
        </div>
    </div>
</div>

{% endblock content %}

templates/article/update.html
{% extends 'base.html' %} {% load staticfiles %}
{% block title %} 修改文章 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <!-- 在value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>
                <!-- 文章栏目 -->
                <div class="form-group">
                    <label for="column">栏目</label>
                    <select class="form-control"
                            id="column"
                            name="column"
                            >
                            <option value="none">请选择栏目..</option>
                        {% for column in columns %}
                            <option value="{{ column.id }}"
                                {% if column.id == article.column.id %}
                                    selected
                                {% endif %}
                            >
                                {{ column }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}